"""initial schema

Revision ID: 6548ac11343f
Revises: 
Create Date: 2026-08-06 15:47:18.727314
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '6548ac11343f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("action IN ('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE')", name=op.f('ck_audit_logs_action')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_entity_id_created_at', 'audit_logs', ['entity_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_record', 'audit_logs', ['table_name', 'record_id', 'created_at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_en', sa.String(length=160), nullable=False),
    sa.Column('display_name_pt', sa.String(length=160), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('brand_axis', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("domain IN ('GROCERY', 'BANKING', 'HEALTH', 'UTILITY', 'VEHICLE', 'OTHER')", name=op.f('ck_categories_domain')),
    sa.CheckConstraint('(level = 1 AND parent_id IS NULL) OR (level > 1 AND parent_id IS NOT NULL)', name=op.f('ck_categories_ck_categories_level_parent')),
    sa.CheckConstraint('level BETWEEN 1 AND 3', name=op.f('ck_categories_ck_categories_level')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('domain', 'code_en', name='uq_categories_domain_code_en')
    )
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('signed_url_expires_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("source IN ('URL', 'UPLOAD')", name=op.f('ck_documents_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_sha256_hash', 'documents', ['sha256_hash'], unique=False)
    op.create_table('households',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    op.create_table('links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_type', sa.String(length=64), nullable=False),
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('to_type', sa.String(length=64), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=48), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('decision_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("link_type IN ('RECEIPT_TRANSACTION', 'CLAIM_TRANSACTION', 'BILL_TRANSACTION', 'VEHICLE_EXPENSE_TRANSACTION', 'OTHER')", name=op.f('ck_links_link_type')),
    sa.CheckConstraint("status IN ('SUGGESTED', 'CONFIRMED', 'DISMISSED')", name=op.f('ck_links_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_links'))
    )
    op.create_index('ix_links_from', 'links', ['from_type', 'from_id'], unique=False)
    op.create_index('ix_links_to', 'links', ['to_type', 'to_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING')", name=op.f('ck_processing_jobs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs')),
    sa.UniqueConstraint('idempotency_key', name='uq_processing_jobs_idempotency_key')
    )
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("scope IN ('GLOBAL', 'HOUSEHOLD', 'ENTITY', 'MODULE')", name=op.f('ck_settings_scope')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('scope', 'scope_id', 'key', name='uq_settings_scope_scope_id_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_dependent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('OWNER', 'MEMBER', 'VIEWER')", name=op.f('ck_users_ck_users_role')),
    sa.CheckConstraint('NOT (is_dependent AND password_hash IS NOT NULL)', name=op.f('ck_users_ck_users_dependent_has_no_password')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('member_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_readonly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_entities_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('household_id', 'name', name='uq_entities_household_id_name')
    )
    op.create_index('ix_entities_household_id', 'entities', ['household_id'], unique=False)
    op.create_table('household_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('OWNER', 'MEMBER', 'VIEWER')", name=op.f('ck_household_members_ck_household_members_role')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_members_household_id_households')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_members')),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_household_members_household_user')
    )
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nif', sa.String(length=9), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('default_category_l1_id', sa.UUID(), nullable=True),
    sa.Column('default_category_l2_id', sa.UUID(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('RETAIL', 'BANK', 'INSURER', 'UTILITY_PROVIDER', 'SERVICE_PROVIDER', 'OTHER')", name=op.f('ck_merchants_kind')),
    sa.ForeignKeyConstraint(['default_category_l1_id'], ['categories.id'], name=op.f('fk_merchants_default_category_l1_id_categories')),
    sa.ForeignKeyConstraint(['default_category_l2_id'], ['categories.id'], name=op.f('fk_merchants_default_category_l2_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_index('ix_merchants_name', 'merchants', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_tags_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('household_id', 'name', name='uq_tags_household_id_name')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=48), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('file_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source_type IN ('CSV', 'OFX', 'PDF', 'MANUAL')", name=op.f('ck_import_batches_source_type')),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')", name=op.f('ck_import_batches_status')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_import_batches_entity_id_entities')),
    sa.ForeignKeyConstraint(['file_document_id'], ['documents.id'], name=op.f('fk_import_batches_file_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_table('lego_set_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.String(length=32), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('subtheme', sa.String(length=120), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('retired_year', sa.Integer(), nullable=True),
    sa.Column('piece_count', sa.Integer(), nullable=True),
    sa.Column('minifig_count', sa.Integer(), nullable=True),
    sa.Column('rrp_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_value_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('value_updated_at', sa.Date(), nullable=True),
    sa.Column('image_document_id', sa.UUID(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(is_custom = true AND set_number IS NULL) OR is_custom = false', name=op.f('ck_lego_set_models_ck_lego_set_models_custom_has_no_number')),
    sa.CheckConstraint('current_value_eur IS NULL OR current_value_eur >= 0', name=op.f('ck_lego_set_models_ck_lego_set_models_value_non_negative')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_lego_set_models_entity_id_entities')),
    sa.ForeignKeyConstraint(['image_document_id'], ['documents.id'], name=op.f('fk_lego_set_models_image_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lego_set_models'))
    )
    op.create_index('ix_lego_set_models_entity_id_name', 'lego_set_models', ['entity_id', 'name'], unique=False)
    op.create_index('ix_lego_set_models_theme', 'lego_set_models', ['theme'], unique=False)
    op.create_index('uq_lego_set_models_entity_set_number', 'lego_set_models', ['entity_id', 'set_number'], unique=True, postgresql_where=sa.text('set_number IS NOT NULL AND is_deleted = false'))
    op.create_table('lego_storage_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('container', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('capacity_pct', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('capacity_pct IS NULL OR (capacity_pct BETWEEN 0 AND 100)', name=op.f('ck_lego_storage_locations_ck_lego_storage_locations_capacity_range')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_lego_storage_locations_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lego_storage_locations')),
    sa.UniqueConstraint('entity_id', 'area', 'container', name='uq_lego_storage_locations_entity_area_container')
    )
    op.create_table('review_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=48), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('suggested_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'FIXED', 'DISMISSED')", name=op.f('ck_review_tasks_status')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_review_tasks_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_tasks'))
    )
    op.create_index('ix_review_tasks_entity_status', 'review_tasks', ['entity_id', 'status', 'created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_sessions_entity_id_entities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('lego_set_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('lego_set_model_id', sa.UUID(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_cost_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('acquisition_source', sa.String(length=16), nullable=True),
    sa.Column('acquisition_transaction_id', sa.UUID(), nullable=True),
    sa.Column('storage_location_id', sa.UUID(), nullable=True),
    sa.Column('build_state', sa.String(length=16), nullable=True),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('has_box', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('has_instructions', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('missing_parts', sa.Text(), nullable=True),
    sa.Column('ownership_status', sa.String(length=20), server_default='IN_COLLECTION', nullable=False),
    sa.Column('sale_price_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('photo_document_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("acquisition_source IS NULL OR acquisition_source IN ('RETAIL', 'SECONDHAND', 'GIFT', 'OTHER')", name=op.f('ck_lego_set_instances_ck_lego_set_instances_acquisition_source')),
    sa.CheckConstraint("build_state IS NULL OR build_state IN ('SEALED', 'BUILT', 'DISASSEMBLED')", name=op.f('ck_lego_set_instances_ck_lego_set_instances_build_state')),
    sa.CheckConstraint("condition IS NULL OR condition IN ('NEW', 'GOOD', 'WORN', 'DAMAGED')", name=op.f('ck_lego_set_instances_ck_lego_set_instances_condition')),
    sa.CheckConstraint("ownership_status IN ('IN_COLLECTION', 'SOLD', 'GIFTED')", name=op.f('ck_lego_set_instances_ck_lego_set_instances_ownership_status')),
    sa.CheckConstraint('acquisition_cost_eur >= 0', name=op.f('ck_lego_set_instances_ck_lego_set_instances_cost_non_negative')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_lego_set_instances_entity_id_entities')),
    sa.ForeignKeyConstraint(['lego_set_model_id'], ['lego_set_models.id'], name=op.f('fk_lego_set_instances_lego_set_model_id_lego_set_models')),
    sa.ForeignKeyConstraint(['photo_document_id'], ['documents.id'], name=op.f('fk_lego_set_instances_photo_document_id_documents')),
    sa.ForeignKeyConstraint(['storage_location_id'], ['lego_storage_locations.id'], name=op.f('fk_lego_set_instances_storage_location_id_lego_storage_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lego_set_instances'))
    )
    op.create_index('ix_lego_set_instances_entity_status', 'lego_set_instances', ['entity_id', 'ownership_status', 'is_deleted'], unique=False)
    op.create_index('ix_lego_set_instances_model_id', 'lego_set_instances', ['lego_set_model_id'], unique=False)
    op.create_index('ix_lego_set_instances_storage_location_id', 'lego_set_instances', ['storage_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lego_set_instances_storage_location_id', table_name='lego_set_instances')
    op.drop_index('ix_lego_set_instances_model_id', table_name='lego_set_instances')
    op.drop_index('ix_lego_set_instances_entity_status', table_name='lego_set_instances')
    op.drop_table('lego_set_instances')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_review_tasks_entity_status', table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_table('lego_storage_locations')
    op.drop_index('uq_lego_set_models_entity_set_number', table_name='lego_set_models', postgresql_where=sa.text('set_number IS NOT NULL AND is_deleted = false'))
    op.drop_index('ix_lego_set_models_theme', table_name='lego_set_models')
    op.drop_index('ix_lego_set_models_entity_id_name', table_name='lego_set_models')
    op.drop_table('lego_set_models')
    op.drop_table('import_batches')
    op.drop_table('tags')
    op.drop_index('ix_merchants_name', table_name='merchants')
    op.drop_table('merchants')
    op.drop_table('household_members')
    op.drop_index('ix_entities_household_id', table_name='entities')
    op.drop_table('entities')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('processing_jobs')
    op.drop_index('ix_links_to', table_name='links')
    op.drop_index('ix_links_from', table_name='links')
    op.drop_table('links')
    op.drop_table('households')
    op.drop_index('ix_documents_sha256_hash', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_audit_logs_record', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_id_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
