"""m1a receipts ingestion spine

Revision ID: b2893bf73034
Revises: 4c1e9b73a5d0
Create Date: 2026-08-17 15:32:17.035174
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'b2893bf73034'
down_revision: str | None = '4c1e9b73a5d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_parser_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('parser_key', sa.String(length=64), nullable=False),
    sa.Column('document_kinds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detection_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('success_rate IS NULL OR (success_rate >= 0 AND success_rate <= 1)', name=op.f('ck_merchant_parser_profiles_success_rate_range')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_merchant_parser_profiles_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_parser_profiles'))
    )
    op.create_index('ix_merchant_parser_profiles_merchant_id', 'merchant_parser_profiles', ['merchant_id'], unique=False)
    op.create_index('uq_merchant_parser_profiles_generic', 'merchant_parser_profiles', ['merchant_id'], unique=True, postgresql_where=sa.text('merchant_id IS NULL AND is_deleted = false'))
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('parser_profile_id', sa.UUID(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('processing_job_id', sa.UUID(), nullable=True),
    sa.Column('total_eur', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('total_discount_eur', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('decision_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_ocr_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('atcud_code', sa.String(length=64), nullable=True),
    sa.Column('atcud_valid', sa.Boolean(), nullable=True),
    sa.Column('atcud_reason', sa.String(length=300), nullable=True),
    sa.Column('parsed_payment_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loyalty_scheme', sa.String(length=120), nullable=True),
    sa.Column('loyalty_card_masked', sa.String(length=64), nullable=True),
    sa.Column('loyalty_accrued_eur', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('loyalty_discount_eur', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'VOID' OR void_reason IS NOT NULL", name=op.f('ck_receipts_void_needs_reason')),
    sa.CheckConstraint("status IN ('UPLOADED', 'PARSING', 'AUTO_ACCEPTED', 'NEEDS_REVIEW', 'CONFIRMED', 'VOID', 'FAILED')", name=op.f('ck_receipts_status')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_receipts_confidence_range')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_receipts_document_id_documents')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_receipts_entity_id_entities')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_receipts_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_receipts_merchant_id_merchants')),
    sa.ForeignKeyConstraint(['parser_profile_id'], ['merchant_parser_profiles.id'], name=op.f('fk_receipts_parser_profile_id_merchant_parser_profiles')),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], name=op.f('fk_receipts_processing_job_id_processing_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts'))
    )
    op.create_index('ix_receipts_entity_purchase_date_id', 'receipts', ['entity_id', 'purchase_date', 'id'], unique=False)
    op.create_index('ix_receipts_merchant_id', 'receipts', ['merchant_id'], unique=False)
    op.create_index('ix_receipts_status', 'receipts', ['status'], unique=False)
    op.create_index('uq_receipts_entity_atcud', 'receipts', ['entity_id', 'atcud_code'], unique=True, postgresql_where=sa.text('atcud_code IS NOT NULL AND is_deleted = false'))
    op.create_index('uq_receipts_entity_document', 'receipts', ['entity_id', 'document_id'], unique=True, postgresql_where=sa.text('document_id IS NOT NULL AND is_deleted = false'))
    op.create_table('receipt_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('merchant_section', sa.String(length=120), nullable=True),
    sa.Column('description_raw', sa.String(length=300), nullable=False),
    sa.Column('description_norm', sa.String(length=300), nullable=False),
    sa.Column('master_product_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), server_default='1', nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('quantity_canonical', sa.Numeric(precision=14, scale=4), server_default='1', nullable=False),
    sa.Column('unit_canonical', sa.String(length=8), nullable=False),
    sa.Column('weight_listed_kg', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('weight_observed_kg', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('is_bulk_weighed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('unit_price_pvp_eur', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('promo_discount_eur', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('promo_type', sa.String(length=16), nullable=True),
    sa.Column('invoice_allocated_discount_eur', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('paid_price_eur', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('iva_class_raw', sa.String(length=4), nullable=True),
    sa.Column('is_fs', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notional_value_source', sa.String(length=20), nullable=True),
    sa.Column('product_flag', sa.String(length=20), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('legacy_row_ref', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('decision_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("notional_value_source IS NULL OR notional_value_source IN ('PRICE_HISTORY', 'MANUAL')", name=op.f('ck_receipt_items_notional_value_source')),
    sa.CheckConstraint("product_flag IS NULL OR product_flag IN ('REFUND', 'DEPOSIT_RETURN', 'SEASONAL', 'OTHER')", name=op.f('ck_receipt_items_product_flag')),
    sa.CheckConstraint("promo_type IS NULL OR promo_type IN ('ABSOLUTE', 'PERCENTAGE', 'BOGO')", name=op.f('ck_receipt_items_promo_type')),
    sa.CheckConstraint("unit IN ('KG', 'G', 'L', 'ML', 'UN', 'PACK')", name=op.f('ck_receipt_items_unit')),
    sa.CheckConstraint("unit_canonical IN ('KG', 'L', 'UN')", name=op.f('ck_receipt_items_unit_canonical')),
    sa.CheckConstraint('is_fs = false OR (line_no IS NULL AND merchant_section IS NULL AND iva_class_raw IS NULL)', name=op.f('ck_receipt_items_fs_has_no_document_fields')),
    sa.CheckConstraint('is_fs = false OR paid_price_eur = 0', name=op.f('ck_receipt_items_fs_pays_nothing')),
    sa.CheckConstraint('is_fs = false OR unit_price_pvp_eur > 0', name=op.f('ck_receipt_items_fs_needs_notional_value')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_receipt_items_entity_id_entities')),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name=op.f('fk_receipt_items_receipt_id_receipts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_items'))
    )
    op.create_index('ix_receipt_items_entity_id', 'receipt_items', ['entity_id'], unique=False)
    op.create_index('ix_receipt_items_master_product_id', 'receipt_items', ['master_product_id'], unique=False)
    op.create_index('ix_receipt_items_receipt_id_line_no', 'receipt_items', ['receipt_id', 'line_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipt_items_receipt_id_line_no', table_name='receipt_items')
    op.drop_index('ix_receipt_items_master_product_id', table_name='receipt_items')
    op.drop_index('ix_receipt_items_entity_id', table_name='receipt_items')
    op.drop_table('receipt_items')
    op.drop_index('uq_receipts_entity_document', table_name='receipts', postgresql_where=sa.text('document_id IS NOT NULL AND is_deleted = false'))
    op.drop_index('uq_receipts_entity_atcud', table_name='receipts', postgresql_where=sa.text('atcud_code IS NOT NULL AND is_deleted = false'))
    op.drop_index('ix_receipts_status', table_name='receipts')
    op.drop_index('ix_receipts_merchant_id', table_name='receipts')
    op.drop_index('ix_receipts_entity_purchase_date_id', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index('uq_merchant_parser_profiles_generic', table_name='merchant_parser_profiles', postgresql_where=sa.text('merchant_id IS NULL AND is_deleted = false'))
    op.drop_index('ix_merchant_parser_profiles_merchant_id', table_name='merchant_parser_profiles')
    op.drop_table('merchant_parser_profiles')
    # ### end Alembic commands ###
