"""m1b product catalogue and taxonomy

Revision ID: baf648f645a8
Revises: b2893bf73034
Create Date: 2026-08-17 16:14:04.827830
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'baf648f645a8'
down_revision: str | None = 'b2893bf73034'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=250), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_l1_id', sa.UUID(), nullable=True),
    sa.Column('category_l2_id', sa.UUID(), nullable=True),
    sa.Column('category_l3_id', sa.UUID(), nullable=True),
    sa.Column('category_status', sa.String(length=16), server_default='AUTO', nullable=False),
    sa.Column('category_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('pack_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sold_by_weight', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dietary_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergen_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seasonal_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('deposit_value_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category_status IN ('AUTO', 'VALIDATED', 'MANUAL')", name=op.f('ck_master_products_category_status')),
    sa.CheckConstraint('category_confidence IS NULL OR (category_confidence >= 0 AND category_confidence <= 1)', name=op.f('ck_master_products_category_confidence_range')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_master_products_category_id_categories')),
    sa.ForeignKeyConstraint(['category_l1_id'], ['categories.id'], name=op.f('fk_master_products_category_l1_id_categories')),
    sa.ForeignKeyConstraint(['category_l2_id'], ['categories.id'], name=op.f('fk_master_products_category_l2_id_categories')),
    sa.ForeignKeyConstraint(['category_l3_id'], ['categories.id'], name=op.f('fk_master_products_category_l3_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_products'))
    )
    op.create_index('ix_master_products_canonical_name', 'master_products', ['canonical_name'], unique=False)
    op.create_index('ix_master_products_category_l1_id_l2_id_l3_id', 'master_products', ['category_l1_id', 'category_l2_id', 'category_l3_id'], unique=False)
    op.create_index('uq_master_products_canonical_name_brand', 'master_products', ['canonical_name', 'brand'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('product_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_product_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_description', sa.String(length=300), nullable=False),
    sa.Column('description_norm', sa.String(length=300), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), server_default='0.5', nullable=False),
    sa.Column('correction_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_product_aliases_confidence_range')),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], name=op.f('fk_product_aliases_master_product_id_master_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_product_aliases_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_aliases')),
    sa.UniqueConstraint('merchant_id', 'description_norm', name='uq_product_aliases_merchant_description')
    )
    op.create_index('ix_product_aliases_master_product_id', 'product_aliases', ['master_product_id'], unique=False)
    op.create_foreign_key(op.f('fk_receipt_items_master_product_id_master_products'), 'receipt_items', 'master_products', ['master_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_receipt_items_master_product_id_master_products'), 'receipt_items', type_='foreignkey')
    op.drop_index('ix_product_aliases_master_product_id', table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_index('uq_master_products_canonical_name_brand', table_name='master_products', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_master_products_category_l1_id_l2_id_l3_id', table_name='master_products')
    op.drop_index('ix_master_products_canonical_name', table_name='master_products')
    op.drop_table('master_products')
    # ### end Alembic commands ###
