"""m1c product price history

Revision ID: c959ddb96cc3
Revises: baf648f645a8
Create Date: 2026-08-17 17:19:09.444647
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c959ddb96cc3'
down_revision: str | None = 'baf648f645a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_product_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('is_fs', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('list_price_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_price_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source_receipt_item_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0', name=op.f('ck_product_price_history_weight_positive')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_product_price_history_entity_id_entities')),
    sa.ForeignKeyConstraint(['master_product_id'], ['master_products.id'], name=op.f('fk_product_price_history_master_product_id_master_products')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_product_price_history_merchant_id_merchants')),
    sa.ForeignKeyConstraint(['source_receipt_item_id'], ['receipt_items.id'], name=op.f('fk_product_price_history_source_receipt_item_id_receipt_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_price_history'))
    )
    op.create_index('ix_product_price_history_product_merchant_observed', 'product_price_history', ['master_product_id', 'merchant_id', 'observed_on'], unique=False)
    op.create_index('ix_product_price_history_source_item', 'product_price_history', ['source_receipt_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_price_history_source_item', table_name='product_price_history')
    op.drop_index('ix_product_price_history_product_merchant_observed', table_name='product_price_history')
    op.drop_table('product_price_history')
    # ### end Alembic commands ###
