/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_auth_profile_patch"];
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_members_get"];
        put?: never;
        /** Create Member */
        post: operations["create_member_api_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_members__member_id__delete"];
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_api_members__member_id__patch"];
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entities */
        get: operations["list_entities_api_entities_get"];
        put?: never;
        /** Create Entity */
        post: operations["create_entity_api_entities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Entity */
        patch: operations["update_entity_api_entities__entity_id__patch"];
        trace?: never;
    };
    "/api/sessions/entity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch Entity */
        post: operations["switch_entity_api_sessions_entity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Merchants */
        get: operations["list_merchants_api_merchants_get"];
        put?: never;
        /** Create Merchant */
        post: operations["create_merchant_api_merchants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchants/{merchant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Merchant */
        delete: operations["delete_merchant_api_merchants__merchant_id__delete"];
        options?: never;
        head?: never;
        /** Update Merchant */
        patch: operations["update_merchant_api_merchants__merchant_id__patch"];
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lego/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_lego_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lego/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_lego_models_get"];
        put?: never;
        /** Create Model */
        post: operations["create_model_api_lego_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lego/models/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lookup
         * @description Contacts Brickset only here — on an explicit user action (M9 guarantee).
         */
        post: operations["lookup_api_lego_models_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lego/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_api_lego_models__model_id__get"];
        put?: never;
        post?: never;
        /** Delete Model */
        delete: operations["delete_model_api_lego_models__model_id__delete"];
        options?: never;
        head?: never;
        /** Update Model */
        patch: operations["update_model_api_lego_models__model_id__patch"];
        trace?: never;
    };
    "/api/lego/models/{model_id}/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Instances */
        get: operations["model_instances_api_lego_models__model_id__instances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lego/models/{model_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Model Image */
        put: operations["set_model_image_api_lego_models__model_id__image_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lego/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instances */
        get: operations["list_instances_api_lego_instances_get"];
        put?: never;
        /** Create Instance */
        post: operations["create_instance_api_lego_instances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lego/instances/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instance */
        get: operations["get_instance_api_lego_instances__instance_id__get"];
        put?: never;
        post?: never;
        /** Delete Instance */
        delete: operations["delete_instance_api_lego_instances__instance_id__delete"];
        options?: never;
        head?: never;
        /** Update Instance */
        patch: operations["update_instance_api_lego_instances__instance_id__patch"];
        trace?: never;
    };
    "/api/lego/instances/{instance_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Instance Photo */
        put: operations["set_instance_photo_api_lego_instances__instance_id__photo_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lego/storage-locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Storage */
        get: operations["list_storage_api_lego_storage_locations_get"];
        put?: never;
        /** Create Storage */
        post: operations["create_storage_api_lego_storage_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lego/storage-locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Storage */
        get: operations["get_storage_api_lego_storage_locations__location_id__get"];
        put?: never;
        post?: never;
        /** Delete Storage */
        delete: operations["delete_storage_api_lego_storage_locations__location_id__delete"];
        options?: never;
        head?: never;
        /** Update Storage */
        patch: operations["update_storage_api_lego_storage_locations__location_id__patch"];
        trace?: never;
    };
    "/api/documents/{document_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content */
        get: operations["get_content_api_documents__document_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_review_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_review_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/tasks/{task_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve */
        post: operations["resolve_api_review_tasks__task_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest */
        get: operations["suggest_api_transactions_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityItem */
        ActivityItem: {
            /** Id */
            id: string;
            /** Action */
            action: string;
            /** Table Name */
            table_name: string;
            /** Record Id */
            record_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Actor Display Name */
            actor_display_name?: string | null;
        };
        /** Body_set_instance_photo_api_lego_instances__instance_id__photo_put */
        Body_set_instance_photo_api_lego_instances__instance_id__photo_put: {
            /** File */
            file?: string | null;
        };
        /** Body_set_model_image_api_lego_models__model_id__image_put */
        Body_set_model_image_api_lego_models__model_id__image_put: {
            /** File */
            file?: string | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code En */
            code_en: string;
            /** Display Name Pt */
            display_name_pt: string;
            /** Domain */
            domain: string;
            /** Level */
            level: number;
            /** Parent Id */
            parent_id: string | null;
            /** Brand Axis */
            brand_axis: boolean;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Tiles */
            tiles: components["schemas"]["ModuleTile"][];
            /** Pending Reviews */
            pending_reviews: number;
            /** Recent Activity */
            recent_activity: components["schemas"]["ActivityItem"][];
        };
        /** EntityCreate */
        EntityCreate: {
            /** Name */
            name: string;
            /** Member Ids */
            member_ids: string[];
            /** Color */
            color?: string | null;
        };
        /** EntityOut */
        EntityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Member Ids */
            member_ids: string[];
            /** Color */
            color: string | null;
            /** Is Readonly */
            is_readonly: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EntitySwitch */
        EntitySwitch: {
            /** Entity Id */
            entity_id?: string | null;
        };
        /** EntitySwitchResult */
        EntitySwitchResult: {
            /** Active Entity Id */
            active_entity_id: string | null;
            /** Csrf Token */
            csrf_token: string;
        };
        /** EntityUpdate */
        EntityUpdate: {
            /** Name */
            name?: string | null;
            /** Member Ids */
            member_ids?: string[] | null;
            /** Color */
            color?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LegoSetInstanceCreate */
        LegoSetInstanceCreate: {
            /** Acquisition Date */
            acquisition_date?: string | null;
            /**
             * Acquisition Cost Eur
             * @default 0.00
             */
            acquisition_cost_eur: number | string;
            /** Acquisition Source */
            acquisition_source?: ("RETAIL" | "SECONDHAND" | "GIFT" | "OTHER") | null;
            /** Acquisition Transaction Id */
            acquisition_transaction_id?: string | null;
            /** Storage Location Id */
            storage_location_id?: string | null;
            /** Build State */
            build_state?: ("SEALED" | "BUILT" | "DISASSEMBLED") | null;
            /** Condition */
            condition?: ("NEW" | "GOOD" | "WORN" | "DAMAGED") | null;
            /**
             * Has Box
             * @default true
             */
            has_box: boolean;
            /**
             * Has Instructions
             * @default true
             */
            has_instructions: boolean;
            /** Missing Parts */
            missing_parts?: string | null;
            /** Notes */
            notes?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Lego Set Model Id */
            lego_set_model_id?: string | null;
            new_set?: components["schemas"]["LegoSetModelCreate"] | null;
        };
        /** LegoSetInstanceOut */
        LegoSetInstanceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /**
             * Lego Set Model Id
             * Format: uuid
             */
            lego_set_model_id: string;
            /** Acquisition Date */
            acquisition_date: string | null;
            /** Acquisition Cost Eur */
            acquisition_cost_eur: string;
            /** Acquisition Source */
            acquisition_source: ("RETAIL" | "SECONDHAND" | "GIFT" | "OTHER") | null;
            /** Acquisition Transaction Id */
            acquisition_transaction_id: string | null;
            /** Storage Location Id */
            storage_location_id: string | null;
            /** Build State */
            build_state: ("SEALED" | "BUILT" | "DISASSEMBLED") | null;
            /** Condition */
            condition: ("NEW" | "GOOD" | "WORN" | "DAMAGED") | null;
            /** Has Box */
            has_box: boolean;
            /** Has Instructions */
            has_instructions: boolean;
            /** Missing Parts */
            missing_parts: string | null;
            /**
             * Ownership Status
             * @enum {string}
             */
            ownership_status: "IN_COLLECTION" | "SOLD" | "GIFTED";
            /** Sale Price Eur */
            sale_price_eur: string | null;
            /** Sale Date */
            sale_date: string | null;
            /** Photo Document Id */
            photo_document_id: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Is Complete
             * @default true
             */
            is_complete: boolean;
            /** Current Value Eur */
            current_value_eur?: string | null;
            /** Appreciation Eur */
            appreciation_eur?: string | null;
            /** Roi Pct */
            roi_pct?: string | null;
            /** Storage Label */
            storage_label?: string | null;
            set_model?: components["schemas"]["LegoSetModelOut"] | null;
        };
        /** LegoSetInstanceUpdate */
        LegoSetInstanceUpdate: {
            /** Acquisition Date */
            acquisition_date?: string | null;
            /** Acquisition Cost Eur */
            acquisition_cost_eur?: number | string | null;
            /** Acquisition Source */
            acquisition_source?: ("RETAIL" | "SECONDHAND" | "GIFT" | "OTHER") | null;
            /** Acquisition Transaction Id */
            acquisition_transaction_id?: string | null;
            /** Storage Location Id */
            storage_location_id?: string | null;
            /** Build State */
            build_state?: ("SEALED" | "BUILT" | "DISASSEMBLED") | null;
            /** Condition */
            condition?: ("NEW" | "GOOD" | "WORN" | "DAMAGED") | null;
            /** Has Box */
            has_box?: boolean | null;
            /** Has Instructions */
            has_instructions?: boolean | null;
            /** Missing Parts */
            missing_parts?: string | null;
            /** Notes */
            notes?: string | null;
            /** Ownership Status */
            ownership_status?: ("IN_COLLECTION" | "SOLD" | "GIFTED") | null;
            /** Sale Price Eur */
            sale_price_eur?: number | string | null;
            /** Sale Date */
            sale_date?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /**
             * Clear Storage Location
             * @default false
             */
            clear_storage_location: boolean;
            /**
             * Clear Transaction Link
             * @default false
             */
            clear_transaction_link: boolean;
        };
        /** LegoSetModelCreate */
        LegoSetModelCreate: {
            /** Set Number */
            set_number?: string | null;
            /**
             * Is Custom
             * @default false
             */
            is_custom: boolean;
            /** Name */
            name: string;
            /** Theme */
            theme?: string | null;
            /** Subtheme */
            subtheme?: string | null;
            /** Release Year */
            release_year?: number | null;
            /** Retired Year */
            retired_year?: number | null;
            /** Piece Count */
            piece_count?: number | null;
            /** Minifig Count */
            minifig_count?: number | null;
            /** Rrp Eur */
            rrp_eur?: number | string | null;
            /** Current Value Eur */
            current_value_eur?: number | string | null;
            /** Short Description */
            short_description?: string | null;
            /** Notes */
            notes?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Image Url */
            image_url?: string | null;
        };
        /** LegoSetModelOut */
        LegoSetModelOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Set Number */
            set_number: string | null;
            /** Is Custom */
            is_custom: boolean;
            /** Name */
            name: string;
            /** Theme */
            theme: string | null;
            /** Subtheme */
            subtheme: string | null;
            /** Release Year */
            release_year: number | null;
            /** Retired Year */
            retired_year: number | null;
            /** Piece Count */
            piece_count: number | null;
            /** Minifig Count */
            minifig_count: number | null;
            /** Rrp Eur */
            rrp_eur: string | null;
            /** Current Value Eur */
            current_value_eur: string | null;
            /** Value Updated At */
            value_updated_at: string | null;
            /** Image Document Id */
            image_document_id: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Short Description */
            short_description: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Is Retired
             * @default false
             */
            is_retired: boolean;
            /**
             * Value Is Stale
             * @default false
             */
            value_is_stale: boolean;
            /** Value Age Days */
            value_age_days?: number | null;
            /**
             * Owned Copies Count
             * @default 0
             */
            owned_copies_count: number;
        };
        /** LegoSetModelUpdate */
        LegoSetModelUpdate: {
            /** Set Number */
            set_number?: string | null;
            /** Name */
            name?: string | null;
            /** Theme */
            theme?: string | null;
            /** Subtheme */
            subtheme?: string | null;
            /** Release Year */
            release_year?: number | null;
            /** Retired Year */
            retired_year?: number | null;
            /** Piece Count */
            piece_count?: number | null;
            /** Minifig Count */
            minifig_count?: number | null;
            /** Rrp Eur */
            rrp_eur?: number | string | null;
            /** Current Value Eur */
            current_value_eur?: number | string | null;
            /** Short Description */
            short_description?: string | null;
            /** Notes */
            notes?: string | null;
            /** Entity Id */
            entity_id?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LookupRequest */
        LookupRequest: {
            /** Set Number */
            set_number: string;
        };
        /** LookupResult */
        LookupResult: {
            /** Found */
            found: boolean;
            /**
             * Provider
             * @default brickset
             */
            provider: string;
            /** Message */
            message?: string | null;
            /** Set Number */
            set_number?: string | null;
            /** Name */
            name?: string | null;
            /** Theme */
            theme?: string | null;
            /** Subtheme */
            subtheme?: string | null;
            /** Release Year */
            release_year?: number | null;
            /** Retired Year */
            retired_year?: number | null;
            /** Piece Count */
            piece_count?: number | null;
            /** Minifig Count */
            minifig_count?: number | null;
            /** Rrp Eur */
            rrp_eur?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Short Description */
            short_description?: string | null;
        };
        /** MemberCreate */
        MemberCreate: {
            /** Display Name */
            display_name: string;
            /** Email */
            email?: string | null;
            /**
             * Role
             * @default MEMBER
             * @enum {string}
             */
            role: "OWNER" | "MEMBER" | "VIEWER";
            /** Temporary Password */
            temporary_password?: string | null;
            /**
             * Is Dependent
             * @default false
             */
            is_dependent: boolean;
        };
        /** MemberOut */
        MemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "OWNER" | "MEMBER" | "VIEWER";
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            /** Left At */
            left_at: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** Is Dependent */
            is_dependent: boolean;
            /** Is Active */
            is_active: boolean;
        };
        /** MemberUpdate */
        MemberUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Role */
            role?: ("OWNER" | "MEMBER" | "VIEWER") | null;
            /** Is Dependent */
            is_dependent?: boolean | null;
            /** New Password */
            new_password?: string | null;
        };
        /** MerchantIn */
        MerchantIn: {
            /** Name */
            name: string;
            /** Nif */
            nif?: string | null;
            /**
             * Kind
             * @default OTHER
             */
            kind: string;
            /** Website */
            website?: string | null;
            /** Aliases */
            aliases?: string[];
        };
        /** MerchantOut */
        MerchantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Nif */
            nif: string | null;
            /** Kind */
            kind: string;
            /** Website */
            website: string | null;
            /** Aliases */
            aliases: string[];
        };
        /** ModuleTile */
        ModuleTile: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "LIVE" | "PLANNED";
            /** Primary Value */
            primary_value?: string | null;
            /** Primary Label */
            primary_label?: string | null;
            /** Secondary Value */
            secondary_value?: string | null;
            /** Secondary Label */
            secondary_label?: string | null;
            /** Href */
            href?: string | null;
        };
        /** Ok */
        Ok: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Message */
            message?: string | null;
        };
        /** OverviewOut */
        OverviewOut: {
            /** Total Cost Eur */
            total_cost_eur: string;
            /** Total Value Eur */
            total_value_eur: string;
            /** Unrealized Gain Eur */
            unrealized_gain_eur: string;
            /** Roi Pct */
            roi_pct: string | null;
            /** Unique Sets */
            unique_sets: number;
            /** Copies Owned */
            copies_owned: number;
            /** Total Pieces */
            total_pieces: number;
            /** Total Minifigs */
            total_minifigs: number;
            /** Retired Sets */
            retired_sets: number;
            /** Models Without Value */
            models_without_value: number;
            /** Stale Value Models */
            stale_value_models: number;
            /** Oldest Value Updated At */
            oldest_value_updated_at: string | null;
            /** Stale Threshold Days */
            stale_threshold_days: number;
            /** Departed Copies */
            departed_copies: number;
            /** Departed Sale Total Eur */
            departed_sale_total_eur: string;
            /** Themes */
            themes: components["schemas"]["ThemeBreakdown"][];
            /** Top Gainers */
            top_gainers: components["schemas"]["LegoSetInstanceOut"][];
            /** Top Losers */
            top_losers: components["schemas"]["LegoSetInstanceOut"][];
            /** Locations Full */
            locations_full: number;
            /** Locations Total */
            locations_total: number;
        };
        /** Page[LegoSetInstanceOut] */
        Page_LegoSetInstanceOut_: {
            /** Items */
            items: components["schemas"]["LegoSetInstanceOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[LegoSetModelOut] */
        Page_LegoSetModelOut_: {
            /** Items */
            items: components["schemas"]["LegoSetModelOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[ReviewTaskOut] */
        Page_ReviewTaskOut_: {
            /** Items */
            items: components["schemas"]["ReviewTaskOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Locale */
            locale?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** ReviewResolution */
        ReviewResolution: {
            /**
             * Action
             * @enum {string}
             */
            action: "CONFIRMED" | "FIXED" | "DISMISSED";
            /** Payload */
            payload?: Record<string, never> | null;
        };
        /** ReviewSummary */
        ReviewSummary: {
            /** Pending */
            pending: number;
            /** By Module */
            by_module: {
                [key: string]: number;
            };
        };
        /** ReviewTaskOut */
        ReviewTaskOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Module */
            module: string;
            /** Subject Type */
            subject_type: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Confidence */
            confidence: number | null;
            /** Suggested Payload */
            suggested_payload: Record<string, never>;
            /** Decision Reasons */
            decision_reasons: unknown[];
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** SessionOut */
        SessionOut: {
            user: components["schemas"]["UserOut"];
            /**
             * Household Id
             * Format: uuid
             */
            household_id: string;
            /** Household Name */
            household_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "OWNER" | "MEMBER" | "VIEWER";
            /** Active Entity Id */
            active_entity_id: string | null;
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Values */
            values: Record<string, never>;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Values */
            values: Record<string, never>;
        };
        /** StorageLocationCreate */
        StorageLocationCreate: {
            /** Area */
            area: string;
            /** Container */
            container?: string | null;
            /** Description */
            description?: string | null;
            /** Capacity Pct */
            capacity_pct?: number | null;
            /** Entity Id */
            entity_id?: string | null;
        };
        /** StorageLocationOut */
        StorageLocationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Area */
            area: string;
            /** Container */
            container: string | null;
            /** Description */
            description: string | null;
            /** Capacity Pct */
            capacity_pct: number | null;
            /** Label */
            label: string;
            /**
             * Stored Count
             * @default 0
             */
            stored_count: number;
            /**
             * Stored Value Eur
             * @default 0.00
             */
            stored_value_eur: string;
            /** Remaining Capacity Pct */
            remaining_capacity_pct?: number | null;
            /**
             * Is Full
             * @default false
             */
            is_full: boolean;
        };
        /** StorageLocationUpdate */
        StorageLocationUpdate: {
            /** Area */
            area?: string | null;
            /** Container */
            container?: string | null;
            /** Description */
            description?: string | null;
            /** Capacity Pct */
            capacity_pct?: number | null;
        };
        /** SuggestionResponse */
        SuggestionResponse: {
            /** Ledger Available */
            ledger_available: boolean;
            /** Message */
            message?: string | null;
            /** Items */
            items: components["schemas"]["TransactionSuggestion"][];
        };
        /** TagIn */
        TagIn: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
        };
        /** TagOut */
        TagOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color: string | null;
        };
        /** ThemeBreakdown */
        ThemeBreakdown: {
            /** Theme */
            theme: string;
            /** Copies */
            copies: number;
            /** Unique Sets */
            unique_sets: number;
            /** Cost Eur */
            cost_eur: string;
            /** Value Eur */
            value_eur: string;
        };
        /** TransactionSuggestion */
        TransactionSuggestion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Booked Date
             * Format: date
             */
            booked_date: string;
            /** Description */
            description: string;
            /** Amount Eur */
            amount_eur: string;
            /** Account Label */
            account_label?: string | null;
            /** Score */
            score: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string | null;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "OWNER" | "MEMBER" | "VIEWER";
            /** Is Dependent */
            is_dependent: boolean;
            /** Must Change Password */
            must_change_password: boolean;
            /** Locale */
            locale: string;
            /** Timezone */
            timezone: string;
            /** Is Deleted */
            is_deleted: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    change_password_api_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_auth_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
        };
    };
    create_member_api_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_api_entities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"][];
                };
            };
        };
    };
    create_entity_api_entities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entity_api_entities__entity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_entity_api_sessions_entity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntitySwitch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySwitchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_merchants_api_merchants_get: {
        parameters: {
            query?: {
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_merchant_api_merchants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_merchant_api_merchants__merchant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_merchant_api_merchants__merchant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MerchantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: {
                domain?: string | null;
                level?: number | null;
                parent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    create_tag_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_lego_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
        };
    };
    list_models_api_lego_models_get: {
        parameters: {
            query?: {
                search?: string | null;
                theme?: string | null;
                stale_only?: boolean;
                no_value_only?: boolean;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LegoSetModelOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_model_api_lego_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegoSetModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegoSetModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_api_lego_models_lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_lego_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegoSetModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_api_lego_models__model_id__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_api_lego_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegoSetModelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegoSetModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_instances_api_lego_models__model_id__instances_get: {
        parameters: {
            query?: {
                ownership_status?: string | null;
            };
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegoSetInstanceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_model_image_api_lego_models__model_id__image_put: {
        parameters: {
            query?: {
                url?: string | null;
            };
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_set_model_image_api_lego_models__model_id__image_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegoSetModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instances_api_lego_instances_get: {
        parameters: {
            query?: {
                search?: string | null;
                theme?: string | null;
                storage_location_id?: string | null;
                build_state?: string | null;
                condition?: string | null;
                ownership_status?: string | null;
                incomplete_only?: boolean;
                retired_only?: boolean;
                sort?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LegoSetInstanceOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_instance_api_lego_instances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegoSetInstanceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegoSetInstanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instance_api_lego_instances__instance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegoSetInstanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_instance_api_lego_instances__instance_id__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_instance_api_lego_instances__instance_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegoSetInstanceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegoSetInstanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_instance_photo_api_lego_instances__instance_id__photo_put: {
        parameters: {
            query?: {
                url?: string | null;
            };
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_set_instance_photo_api_lego_instances__instance_id__photo_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegoSetInstanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_storage_api_lego_storage_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageLocationOut"][];
                };
            };
        };
    };
    create_storage_api_lego_storage_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageLocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageLocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_storage_api_lego_storage_locations__location_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageLocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_storage_api_lego_storage_locations__location_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_storage_api_lego_storage_locations__location_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageLocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageLocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_api_documents__document_id__content_get: {
        parameters: {
            query: {
                expires: number;
                signature: string;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_review_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
        };
    };
    list_tasks_api_review_tasks_get: {
        parameters: {
            query?: {
                status?: string;
                module?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReviewTaskOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_api_review_tasks__task_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewResolution"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_transactions_suggest_get: {
        parameters: {
            query?: {
                near_date?: string | null;
                amount_eur?: number | string | null;
                search?: string | null;
                window_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
}
