/**
 * Domain types, derived from the generated OpenAPI contract.
 *
 * `src/api/schema.d.ts` is generated by `make types-gen` (`./fm types-gen`) — never
 * edit it, and never hand-duplicate a field here. These aliases exist only to give
 * the schema components short, readable names; when the API changes, TypeScript
 * breaks at the call site instead of drifting silently.
 */

import type { components } from '@/api/schema';

type Schemas = components['schemas'];

// --- Identity, household and session ----------------------------------------
export type User = Schemas['UserOut'];
export type Role = User['role'];
export type SessionInfo = Schemas['SessionOut'];
export type Entity = Schemas['EntityOut'];
export type Member = Schemas['MemberOut'];
export type EntitySwitchResult = Schemas['EntitySwitchResult'];
export type Ok = Schemas['Ok'];

// --- LEGO --------------------------------------------------------------------
export type LegoSetModel = Schemas['LegoSetModelOut'];
export type LegoSetInstance = Schemas['LegoSetInstanceOut'];
export type StorageLocation = Schemas['StorageLocationOut'];
export type LegoOverview = Schemas['OverviewOut'];
export type ThemeBreakdown = Schemas['ThemeBreakdown'];
export type LookupResult = Schemas['LookupResult'];

export type AcquisitionSource = NonNullable<LegoSetInstance['acquisition_source']>;
export type BuildState = NonNullable<LegoSetInstance['build_state']>;
export type Condition = NonNullable<LegoSetInstance['condition']>;
export type OwnershipStatus = LegoSetInstance['ownership_status'];

// --- Shared surfaces ---------------------------------------------------------
export type TransactionSuggestion = Schemas['TransactionSuggestion'];
export type SuggestionResponse = Schemas['SuggestionResponse'];
export type Dashboard = Schemas['DashboardOut'];
export type ModuleTile = Schemas['ModuleTile'];
export type ActivityItem = Schemas['ActivityItem'];
export type ReviewSummary = Schemas['ReviewSummary'];
export type ReviewTask = Schemas['ReviewTaskOut'];
export type AppSettings = Schemas['SettingsOut'];

/**
 * Paginated envelope. FastAPI emits one concrete schema per item type
 * (`Page_LegoSetInstanceOut_`, …); this generic keeps the call sites readable.
 */
export interface Page<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
}
