/**
 * Domain types, derived from the generated OpenAPI contract.
 *
 * `src/api/schema.d.ts` is generated by `make types-gen` (`./fm types-gen`) — never
 * edit it, and never hand-duplicate a field here. These aliases exist only to give
 * the schema components short, readable names; when the API changes, TypeScript
 * breaks at the call site instead of drifting silently.
 */

import type { components } from '@/api/schema';

type Schemas = components['schemas'];

// --- Identity, household and session ----------------------------------------
export type User = Schemas['UserOut'];
export type Role = User['role'];
export type SessionInfo = Schemas['SessionOut'];
export type Entity = Schemas['EntityOut'];
export type Member = Schemas['MemberOut'];
export type EntitySwitchResult = Schemas['EntitySwitchResult'];
export type Ok = Schemas['Ok'];

// --- LEGO --------------------------------------------------------------------
export type LegoSetModel = Schemas['LegoSetModelOut'];
export type LegoSetInstance = Schemas['LegoSetInstanceOut'];
export type StorageLocation = Schemas['StorageLocationOut'];
export type LegoOverview = Schemas['OverviewOut'];
export type ThemeBreakdown = Schemas['ThemeBreakdown'];
export type SubthemeBreakdown = Schemas['SubthemeBreakdown'];
export type AreaBreakdown = Schemas['AreaBreakdown'];
export type ChannelBreakdown = Schemas['ChannelBreakdown'];
export type ReleaseYearCount = Schemas['ReleaseYearCount'];
export type BuildStateCount = Schemas['BuildStateCount'];
export type PiecePricePoint = Schemas['PiecePricePoint'];
export type ReleaseYearPiecePoint = Schemas['ReleaseYearPiecePoint'];
export type PieceBracketCount = Schemas['PieceBracketCount'];
export type TimelinePoint = Schemas['TimelinePoint'];
export type CollectionSummary = Schemas['CollectionSummary'];
export type LegoInstancePage = Schemas['LegoSetInstancePage'];
export type LookupResult = Schemas['LookupResult'];
export type LegoSetInstruction = Schemas['LegoSetInstructionOut'];
export type BricksetImport = Schemas['BricksetImportOut'];
export type LegoBricksetJob = Schemas['BricksetJobOut'];
// The preview response and the commit payload are structurally the same shape;
// openapi-typescript splits them into `-Output`/`-Input` only because
// `acquisition_cost_eur` narrows from `number | string` to `string` on the way
// out. `-Output` is used everywhere client-side since the value is always
// normalized to a string before a row is sent back for commit.
export type LegoBulkImportRow = Schemas['BulkImportRow-Output'];
export type LegoBulkImportPreview = Schemas['BulkImportPreviewOut'];
export type LegoBulkImportRowResult = Schemas['BulkImportRowResult'];
export type StorageBulkImportResult = Schemas['StorageBulkImportOut'];
export type BulkSheetsCheck = Schemas['BulkSheetsCheckOut'];

export type AcquisitionSource = NonNullable<LegoSetInstance['acquisition_source']>;
export type BuildState = NonNullable<LegoSetInstance['build_state']>;
export type Condition = NonNullable<LegoSetInstance['condition']>;
export type OwnershipStatus = LegoSetInstance['ownership_status'];

// --- Supermarket & receipts (M1) ---------------------------------------------
export type ReceiptSummary = Schemas['ReceiptSummary'];
export type ReceiptDetail = Schemas['ReceiptDetail'];
export type ReceiptItem = Schemas['ReceiptItemOut'];
export type ProductSummary = Schemas['ProductSummary'];
export type Merchant = Schemas['MerchantOut'];
export type ReceiptDerived = Schemas['ReceiptDerived'];
export type ReceiptStatusBoard = Schemas['StatusBoard'];
export type QueueEntry = Schemas['QueueEntry'];
export type UploadResponse = Schemas['UploadResponse'];
export type ParserProfile = Schemas['ParserProfileOut'];
export type ParserOption = Schemas['ParserOption'];
export type FsFilter = 'all' | 'only' | 'exclude';
export type ReceiptStatus = ReceiptSummary['status'];

// --- Product catalogue and the GROCERY taxonomy (M1b) ------------------------
export type MasterProduct = Schemas['MasterProductOut'];
export type ProductSearchResult = Schemas['ProductSearchResult'];
export type ProductAlias = Schemas['ProductAliasOut'];
export type ProductOccurrence = Schemas['ProductOccurrence'];
export type MergeCandidate = Schemas['MergeCandidate'];
export type CategoryResult = Schemas['CategorySearchResult'];
export type CategoryTreeNode = Schemas['CategoryTreeNode'];
export type CategoryImpact = Schemas['CategoryImpactOut'];
export type CategoryOperationResult = Schemas['CategoryOperationResult'];
export type LegacyImportResult = Schemas['LegacyImportResult'];
export type CategoryStatus = MasterProduct['category_status'];
// Same `-Output`/`-Input` split as the LEGO bulk import, for the same reason
// (`pack_weights_kg` narrows on the way out); `-Output` is what the client uses.
export type BulkProductImportRow = Schemas['BulkProductImportRow-Output'];
export type BulkProductImportPreview = Schemas['BulkProductImportPreviewOut'];
export type BulkProductImportRowResult = Schemas['BulkProductImportRowResult'];

// --- Money over time (M1c) ----------------------------------------------------
export type PricePoint = Schemas['PricePointOut'];
export type PriceHistory = Schemas['PriceHistoryOut'];
export type ShrinkflationSignal = Schemas['ShrinkflationOut'];
export type CategorySpend = Schemas['CategorySpendOut'];
export type LoyaltyGroup = Schemas['LoyaltyGroupOut'];
export type LoyaltyAllocation = Schemas['LoyaltyAllocationOut'];
export type ReceiptLink = Schemas['ReceiptLinkOut'];

/** `{rule, detail, score}` — what the «Porquê?» popover renders. */
export interface DecisionReason {
  rule: string;
  detail: string;
  score?: string | null;
}

// --- Shared surfaces ---------------------------------------------------------
export type TransactionSuggestion = Schemas['TransactionSuggestion'];
export type SuggestionResponse = Schemas['SuggestionResponse'];
export type Dashboard = Schemas['DashboardOut'];
export type ModuleTile = Schemas['ModuleTile'];
export type ActivityItem = Schemas['ActivityItem'];
export type ReviewSummary = Schemas['ReviewSummary'];
export type ReviewTask = Schemas['ReviewTaskOut'];
export type AppSettings = Schemas['SettingsOut'];

/**
 * Paginated envelope. FastAPI emits one concrete schema per item type
 * (`Page_LegoSetInstanceOut_`, …); this generic keeps the call sites readable.
 */
export interface Page<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
}
